affine_trainable: true
auto_save: false
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 3
grid_eps: 0.02
grid_range:
- -1
- 1
k: 5
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 0
symbolic.funs_name.0:
- - sin
  - sinh
  - tanh
  - sin
- - x^2
  - sin
  - sinh
  - x^2
symbolic.funs_name.1:
- - sinh
  - sin
- - sin
  - x^5
- - sinh
  - sinh
- - sinh
  - sinh
- - sin
  - x^2
- - x^2
  - sin
- - x^2
  - sinh
- - x^3
  - sin
symbolic_enabled: true
width:
- - 4
  - 0
- - 2
  - 0
- - 8
  - 0
