affine_trainable: true
auto_save: false
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 4
grid_eps: 0.02
grid_range:
- -1
- 1
k: 4
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 0
symbolic.funs_name.0:
- - tanh
  - tanh
  - x^2
  - sinh
- - sin
  - x
  - sin
  - tanh
- - x
  - tanh
  - tanh
  - tanh
symbolic.funs_name.1:
- - x^3
  - x
  - sin
- - x^2
  - sinh
  - sin
- - sin
  - sinh
  - tanh
- - x^4
  - sinh
  - sin
- - sin
  - x^2
  - sin
- - sinh
  - tanh
  - sin
- - sin
  - tanh
  - sin
- - sin
  - sinh
  - sin
symbolic_enabled: true
width:
- - 4
  - 0
- - 3
  - 0
- - 8
  - 0
