affine_trainable: true
auto_save: false
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 2
grid_eps: 0.02
grid_range:
- -1
- 1
k: 5
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 0
symbolic.funs_name.0:
- - sin
  - x^2
- - sin
  - sin
- - sin
  - sin
symbolic.funs_name.1:
- - sinh
  - x^2
  - x^2
- - x^3
  - x^3
  - sin
- - sin
  - x^2
  - sin
- - sin
  - x^2
  - x
symbolic_enabled: true
width:
- - 2
  - 0
- - 3
  - 0
- - 4
  - 0
